/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./components/subComponents/ColorPicker.vue')['default']
    EditRadioButton: typeof import('./components/subComponents/EditRadioButton.vue')['default']
    EditSection: typeof import('./components/subComponents/EditSection.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    RadioButton: typeof import('./components/subComponents/RadioButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/subComponents/Section.vue')['default']
  }
}
