/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Main: typeof import('./components/Main.vue')['default']
    PageNotFound: typeof import('./components/PageNotFound.vue')['default']
    RadioButton: typeof import('./components/modules/RadioButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/modules/Section.vue')['default']
  }
}
